
[
	Exposed = Window
] interface TangramApplication : EventTarget {

	// Message API
	void addChannel(DOMString channel);
	void removeChannel(DOMString channel);
	void sendMessage(DOMString id, DOMString param1, DOMString param2, DOMString param3, DOMString param4, DOMString param5);

	readonly attribute DOMString name;

	// Event handler attributes
	attribute EventHandler onAppMessageReceived;
};
