typedef sequence<any> ObjectArray;

[
	Exposed = Window
] interface Tangram : EventTarget {

	// Message API
	void wait(boolean bwait);
	void addChannel(DOMString channel);
	void removeChannel(DOMString channel);
	void sendMessage(DOMString id, DOMString param1, DOMString param2, 
		[DefaultValue = Undefined] optional DOMString param3, 
		[DefaultValue = Undefined] optional DOMString param4, 
		[DefaultValue = Undefined] optional DOMString param5);
	void sendMessage(TangramXobj msg,
		[DefaultValue = Undefined] optional ApplicationCallback callback, 
		[DefaultValue = Undefined] optional  boolean bwait);
	void addEventListener(DOMString eventName, ApplicationCallback callback);
	void removeEventListener(DOMString eventName);

	// DOM API
	void defineElement(DOMString tagName, DOMString html);
	void renderElement(DOMString tagName, DOMString html);

	//TangramNode API
	TangramXobj newVar([DefaultValue = Undefined] optional DOMString name);
	TangramNode getNode(long long nodeHandle);
	TangramWindow getWindow(DOMString wndName);
	TangramWindow getWindow(long long wndHandle);

	//TangramWinForm API
	TangramWinform createWinForm(DOMString strFormXml, 
		long FormType, 
		[DefaultValue = Undefined] optional ApplicationCallback callback);

	[Affects = Nothing] getter TangramXobj ? getNamedItem(DOMString name);
	[RaisesException, CEReactions] TangramXobj ? setNamedItem(TangramXobj var);
	[RaisesException, CEReactions] void setNamedItem(DOMString name, TangramXobj var);

	readonly attribute DOMString url;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute TangramXobj xobj;

	// Event handler attributes
	attribute EventHandler onMessageReceived;
	attribute EventHandler onTangramMessageReceived;
	attribute EventHandler onTangramNodeCreated;
	attribute EventHandler onTangramWindowCreated;
	attribute EventHandler onMdiChildActivate;
	attribute EventHandler onWinFormCreated;
	attribute EventHandler onWinFormClosed;
	attribute EventHandler onBindCLRObject;
};
