
[
	Exposed = Window
] interface TangramNode : EventTarget {

	// Message API
	void sendMessage([DefaultValue = Undefined] optional TangramXobj msg,
		[DefaultValue = Undefined] optional ApplicationCallback callback);
	void addEventListener(DOMString eventName, ApplicationCallback callback);
	void addEventListener(DOMString subObjName, DOMString eventName, ApplicationCallback callback);
	void removeEventListener(DOMString eventName);

	void GetControlsNames(ApplicationCallback callback);
	void SyncCtrlTextChange(DOMString strcontrols, [DefaultValue = Undefined] optional ApplicationCallback callback);

	//Control Bind Api:
	void setControlVal(DOMString CtrlID, long long CtrlHandle, DOMString strVal);

	//Node API
	TangramNode getChild(long nIndex);
	TangramNode getChild(long row, long col);
	TangramNode getChild(DOMString strName);
	void open(DOMString strKey, DOMString xml, [DefaultValue = Undefined] optional ApplicationCallback callback);
	void openEx(DOMString strKey, DOMString xml, [DefaultValue = Undefined] optional long row, [DefaultValue = Undefined] optional long col, [DefaultValue = Undefined] optional ApplicationCallback callback);

	readonly attribute long row;
	readonly attribute long col;
	readonly attribute long rows;
	readonly attribute long cols;
	readonly attribute long long handle;
	readonly attribute long long hwnd;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute TangramXobj xobj;
	readonly attribute DOMString name;
	readonly attribute DOMString objtype;

	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute TangramNode rootNode;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute TangramNode parentNode;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute TangramWindow parentWindow;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute TangramWinform parentForm;

	// Event handler attributes
	attribute EventHandler onMessageReceived;
	attribute EventHandler onTangramNodeCreated;
	attribute EventHandler onTangramControlCreated;
	attribute EventHandler onMdiChildActivate;
	attribute EventHandler onWinFormCreated;
	attribute EventHandler onWinFormClosed;
};
