
[
	Exposed = Window
] interface TangramWindow : EventTarget {

	// Message API
	void sendMessage([DefaultValue = Undefined] optional TangramXobj msg,
		[DefaultValue = Undefined] optional ApplicationCallback callback);
	void addEventListener(DOMString eventName, ApplicationCallback callback);
	void removeEventListener(DOMString eventName);

	readonly attribute DOMString name;
	readonly attribute long long handle;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute TangramXobj xobj;

	//TangramNode API
	TangramNode getNode(DOMString nodeName);
	TangramNode getNode(long nodeHandle);

	// Event handler attributes
	attribute EventHandler onMessageReceived;
	attribute EventHandler onTangramNodeCreated;
	attribute EventHandler onMdiChildActivate;
	attribute EventHandler onWinFormCreated;
	attribute EventHandler onWinFormClosed;
};
