
[
	Exposed = Window
] interface TangramNtp : EventTarget {

	// Message API
	void addChannel(DOMString channel);
	void removeChannel(DOMString channel);
	void sendMessage(DOMString id, DOMString param1, DOMString param2, DOMString param3, DOMString param4, DOMString param5);

	Element getElement(DOMString elementname);

	readonly attribute DOMString name;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute TangramXobj xobj;

	// Event handler attributes
	attribute EventHandler onAppNtpReceived;
};
