
[
	Exposed = Window
] interface TangramCompositor : EventTarget {
	readonly attribute DOMString name;

	// Event handler attributes
	attribute EventHandler onMessageReceived;
	attribute EventHandler onTangramNodeCreated;
};
